### ISSUE TITLE
Cho mình hỏi làm sao để lấy được danh sách code trong code.txt với

### ISSUE THREAD

**Issue by TVMD** [HanaIroha/ToolSinhNhatLOL2021#8]

**Comment by HanaIroha** [comment]
Xin lỗi vì giờ mới trả lời bạn, không biết bạn có còn thắc mắc về vấn đề này không. Mình crawl data từ trên page facebook LMHT VN, trong mục bài post phần comment ý ạ. 
Mình sử dụng cả 2:
- https://github.com/X-rus/xNet
- Selenium
